print('Welcome myzama!')
require('myzama.lazy')
require('myzama.treesitter')
require('myzama.remaps')
require('myzama.completions')
require('myzama.lsp_config')
require('myzama.telescope')
require('myzama.harpoon')
require('myzama.vim_settings')
